#docker run  --name clash --log-opt max-size=1m --user 0:1080  --network host -v config.yaml:/root/.config/clash/config.yaml  -v p1.yaml:/p1.yaml -d dreamacro/clash

mixed-port: 7891
redir-port: 12341
allow-lan: true

mode: rule
log-level: info

external-controller: '0.0.0.0:9001'

dns:
  enable: false
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 114.114.114.114 # default value

proxy-providers:
  p1:
    type: file
    interval: 3600
    path: /p1.yaml
    health-check:
        enable: true
        url: http://www.gstatic.com/generate_204
        interval: 300    

proxy-groups:
  - { name: proxy, type: select, use: ["p1"]}

rules:
 - DOMAIN-KEYWORD,bilibili,DIRECT
 - DOMAIN-SUFFIX,google.com,proxy
 - DOMAIN-KEYWORD,google,proxy
 - DOMAIN,google.com,proxy
 - IP-CIDR,127.0.0.0/8,DIRECT
 - IP-CIDR,192.168.1.0/24,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,proxy
