#docker run --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 5901:5901 -d vnc
#docker build -t vnc vncserver

FROM centos:7

ENV container docker
MAINTAINER The CentOS Project <cloud-ops@centos.org>

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
# FROM centos/systemd

MAINTAINER "Your Name" <you@example.com>

RUN yum -y group install GNOME Desktop
RUN yum -y install epel-release
RUN yum -y install cabextract bind-utils traceroute net-tools bash-completion tigervnc-server vim git wget python2-pip
run yum -y install firefox *chinese-fonts*

run pip install pip -U -i https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip install sshuttle

# install config vnc
RUN systemctl stop firewalld.service; \
    systemctl disable firewalld.service; \
    cp /lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@:1.service; \
    systemctl daemon-reload; systemctl enable vncserver@:1.service; \
    echo -e "111111\n111111\nn\n" | vncpasswd

COPY vncserver.service /etc/systemd/system/vncserver@:1.service
RUN yum clean all

CMD ["/usr/sbin/init"]
