#docker build -t registry.cn-shanghai.aliyuncs.com/tty/vnc-8 .
#docker run --privileged -v /root:/sd -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 5901:5901 -d registry.cn-shanghai.aliyuncs.com/tty/vnc-8

# https://en.secnews.gr/204573/centos-8-kde-plasma-install/

FROM centos:8
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

MAINTAINER "Your Name" <you@example.com>

run yum -y group install 'Server with GUI' --skip-broken
run yum -y group install workstation --skip-broken
run yum -y group install 'Development Tools'

RUN yum -y install epel-release; \
    yum -y install bind-utils traceroute net-tools bash-completion tigervnc-server; \
    yum -y install flex bison openssl-devel vim git wget python3-pip firefox xsetroot xterm

run yum install -y python2-devel python2 gcc gcc-c++

run yum install tigervnc-server tigervnc-server-module -y; echo -e "111111\n111111\nn\n" | vncpasswd

run systemctl disable firewalld; \
    systemctl unmask systemd-logind.service; \
    sed -e 's|<USER>|root|' -i /usr/lib/systemd/system/vncserver@.service; \
    systemctl enable vncserver@:1

run rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm; \
    dnf config-manager --enable epel-playground; \
    dnf config-manager --enable PowerTools; \
    dnf -y group install "KDE Plasma Workspaces"; \
    dnf -y group install kde-desktop kde-apps kde-software-Development kf5-software-Development --skip-broken

run dnf -y install switchdesk
