#docker run --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 5901:5901 -d vnc-f31
#docker build -t vnc-f31 .

FROM fedora:31
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]

MAINTAINER "Your Name" <you@example.com>


RUN yum -y group install workstation 'Server with GUI'
RUN yum -y install epel-release; \
    yum -y install bind-utils traceroute net-tools bash-completion tigervnc-server vim git wget python3-pip firefox xsetroot xterm

run yum install -y python2-devel python2 gcc gcc-c++

run yum install tigervnc-server tigervnc-server-module -y; echo -e "111111\n111111\nn\n" | vncpasswd

run systemctl disable firewalld; \
    systemctl unmask systemd-logind.service; \
    sed -e 's|<USER>|root|' -i /usr/lib/systemd/system/vncserver@.service; \
    systemctl enable vncserver@:1

